from EngDict import EngDict

file = open("EN-US-Dictionary.txt", "r")
dictionary = EngDict()
dictionary.LoadDictionary("EN-US-Dictionary.txt")
print(dictionary.PrintDictionarySize())
print("Height of dictionary's tree= " + str(dictionary.RBtree.height(dictionary.RBtree.root)))
print("///////////////////////////////////////////////////")
dictionary.InsertWord("hayam")
print(dictionary.PrintDictionarySize())
print("Height of dictionary's tree= " + str(dictionary.RBtree.height(dictionary.RBtree.root)))
print("///////////////////////////////////////////////////")
dictionary.InsertWord("WimPiesT")
print(dictionary.PrintDictionarySize())
print("Height of dictionary's tree= " + str(dictionary.RBtree.height(dictionary.RBtree.root)))
#dictionary.RBtree.inOrderTraversal(dictionary.RBtree.root)
